### ISSUE TITLE
403 Forbidden response when authenticating with credentials

### ISSUE THREAD

**Issue by splatteredbits** [Inedo/inedox-jenkins#14]
Our Jenkins instance requires authentication. BuildMaster is unable to connect. Jenkins is returning a 403 Forbidden response [1]. I was able to authenticate to Jenkins using PowerShell [2]. I took a look at Jenkins extensions’s source code, it looks like you’re using the Credential property on System.Net.WebClient. I believe WebClient only sends credentials if the servers tries an authentication negotiation (returns a 401 response that includes a WWW-Authenticate header), which Jenkins doesn’t do. You have to explicitly send the authorization header:

```
$bytes = [Text.Encoding]::UTF8.GetBytes('********:********')
$creds = 'Basic ' + [Convert]::ToBase64String($bytes)
$c = New-Object 'Net.WebClient'
$c.Headers.Add('Authorization', $creds)
[xml]$c.DownloadString('https://********/job/********/api/xml') | Select-Object -ExpandProperty 'freeStyleProject'
```

[1]

> Importing artifact "artifact" from Jenkins...
Build number is not an integer, resolving special build number "lastSuccessfulBuild"...
Creating WebClient with username ********...
Downloading string from https://********/job/CMService/api/xml...
Unhandled exception: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.Extensions.Jenkins.JenkinsClient.<GetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.Extensions.Jenkins.JenkinsClient.<GetSpecialBuildNumberAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Inedo.BuildMasterExtensions.Jenkins.JenkinsArtifactImporter.<ImportAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.Extensions.Jenkins.Operations.ImportJenkinsArtifactOperation.<ExecuteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.BuildMaster.Windows.ServiceApplication.Executions.PlanExecuter.DeploymentPlanExecuter.<Inedo-ExecutionEngine-Executer-IExecutionHostEnvironment-ExecuteActionAsync>d__21.MoveNext()
Cleaning up...
Cleanup complete.

[2]

```
$headers = @{ }

$bytes = [Text.Encoding]::UTF8.GetBytes('*******:********')
$creds = 'Basic ' + [Convert]::ToBase64String($bytes)
$headers.Add('Authorization', $creds)

$response = Invoke-WebRequest -UseBasicParsing -Uri 'https://********/job/********/api/xml' 
[xml]$response.Content | Select-Object -ExpandProperty 'freeStyleProject'
```

**Comment by jrasch** [comment]
I'm not sure how long ago this was changed, but it now sets the header directly:

https://github.com/Inedo/inedox-jenkins/blob/master/Jenkins/InedoExtension/JenkinsClient.cs#L34
